apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels: 
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      volumes:
        - name: postgres-storage2
          persistentVolumeClaim: 
            claimName: database-persistent-volume-claim2
      containers:
        - name: postgres
          image: postgres
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                    name: pgpassword
                    key: PGPASSWORD
          ports:
            - containerPort: 5432
          volumeMounts: 
            - name: postgres-storage2
              mountPath: /var/lib/postgresql/data
              subPath: postgres

